# Generated by Django 3.1.7 on 2021-04-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('username', models.CharField(max_length=20)),
                ('github', models.URLField(blank=True)),
                ('github_username', models.TextField(blank=True, max_length=20)),
                ('host', models.TextField(blank=True, max_length=500)),
                ('authorized', models.BooleanField(default=True)),
                ('userid', models.PositiveIntegerField(default=0, null=True)),
                ('email', models.EmailField(default='example@gmail.com', max_length=254)),
                ('name', models.CharField(default='testname', max_length=20)),
                ('consistent_id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('api_token', models.TextField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Author_Privacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.PositiveIntegerField(default=0)),
                ('user_id', models.TextField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.PositiveIntegerField(default=0)),
                ('tag', models.TextField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('post_id', models.PositiveIntegerField(blank=True)),
                ('comment_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('from_user', models.PositiveIntegerField(blank=True, null=True)),
                ('to_user', models.TextField(blank=True, null=True)),
                ('comment_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExternalLike',
            fields=[
                ('like_id', models.PositiveIntegerField(blank=True, primary_key=True, serialize=False)),
                ('from_user', models.TextField()),
                ('to_user', models.TextField(blank=True, max_length=500)),
                ('object', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('author', models.TextField()),
                ('items', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('like_id', models.PositiveIntegerField(blank=True, primary_key=True, serialize=False)),
                ('from_user', models.IntegerField(blank=True)),
                ('to_user', models.TextField(blank=True, max_length=500)),
                ('object', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostserver', models.URLField()),
                ('authusername', models.TextField()),
                ('authpassword', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.TextField(blank=True)),
                ('post_id', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('user_id', models.TextField(blank=True)),
                ('title', models.CharField(default='', max_length=20)),
                ('description', models.CharField(default='', max_length=30)),
                ('markdown', models.BooleanField(default=False)),
                ('content', models.TextField(blank=True, max_length=500)),
                ('image', models.BinaryField(default=b'')),
                ('privfriends', models.BooleanField(default=False)),
                ('unlisted', models.BooleanField(default=False)),
                ('published', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PublicImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usersneedauthentication', models.BooleanField(default=False)),
            ],
        ),
    ]
