# Generated by Django 3.1.7 on 2021-04-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLikes',
            fields=[
                ('like_id', models.PositiveIntegerField(blank=True, primary_key=True, serialize=False)),
                ('from_user', models.IntegerField(blank=True)),
                ('to_user', models.TextField(blank=True, max_length=500)),
                ('post_id', models.PositiveIntegerField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='published',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='externallike',
            name='post_id',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likes',
            name='post_id',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='from_user',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_id',
            field=models.TextField(blank=True),
        ),
    ]
