# Generated by Django 3.1.7 on 2021-03-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreation',
            name='Authorized',
            field=models.BooleanField(default=True),
        ),
    ]
