# Generated by Django 3.1.7 on 2021-03-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('username', models.CharField(max_length=20)),
                ('github', models.URLField(blank=True)),
                ('github_username', models.TextField(blank=True, max_length=20)),
                ('host', models.TextField(blank=True, max_length=500)),
                ('authorized', models.BooleanField(default=True)),
                ('userid', models.PositiveIntegerField(default=0, null=True)),
                ('email', models.EmailField(default='example@gmail.com', max_length=254)),
                ('name', models.CharField(default='testname', max_length=20)),
                ('consistent_id', models.TextField(blank=True, editable=False, max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('from_user', models.PositiveIntegerField(blank=True, null=True)),
                ('to_user', models.PositiveIntegerField(blank=True, null=True)),
                ('comment_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PublicImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UsersNeedAuthentication', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='UserCreation',
        ),
    ]
