# Generated by Django 3.1.7 on 2021-03-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UsersNeedAuthentication', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='usercreation',
            name='authorized',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usercreation',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='usercreation',
            name='name',
            field=models.CharField(default='testname', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercreation',
            name='userid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
