# Generated by Django 3.1.7 on 2021-04-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='origin',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.TextField(blank=True),
        ),
    ]
