# Generated by Django 3.1.6 on 2021-03-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20210328_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('post_id', models.PositiveIntegerField(blank=True)),
                ('comment_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('from_user', models.PositiveIntegerField(blank=True, null=True)),
                ('to_user', models.TextField(blank=True, null=True)),
                ('comment_text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='userid',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
