# Generated by Django 3.1.7 on 2021-03-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20210304_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('github', models.URLField(blank=True)),
                ('host', models.TextField(blank=True, max_length=500)),
                ('authorized', models.BooleanField(default=True)),
                ('userid', models.PositiveIntegerField(default=0)),
                ('email', models.EmailField(default='example@gmail.com', max_length=254)),
                ('name', models.CharField(default='testname', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PublicImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='image/')),
            ],
        ),
        migrations.DeleteModel(
            name='UserCreation',
        ),
    ]
