# Generated by Django 3.1.7 on 2021-03-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20210328_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='author_privacy',
            name='user_id',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
