# Generated by Django 3.1.7 on 2021-03-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20210305_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='PublicImages',
        ),
        migrations.AlterField(
            model_name='author',
            name='consistent_id',
            field=models.TextField(blank=True, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
