# Generated by Django 3.1.7 on 2021-03-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_delete_authorized'),
    ]

    operations = [
        migrations.CreateModel(
            name='authorize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorize', models.BooleanField(default=False)),
            ],
        ),
    ]
