# Generated by Django 3.1.7 on 2021-03-31 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_nodes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nodes',
            new_name='Node',
        ),
    ]
