# Generated by Django 2.1.7 on 2021-03-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20210305_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.PositiveIntegerField(default=0)),
                ('user_id', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(default='', max_length=20)),
                ('description', models.CharField(default='', max_length=30)),
                ('markdown', models.BooleanField(default=False)),
                ('content', models.TextField(blank=True, max_length=500)),
                ('image', models.BinaryField(default=b'')),
                ('tstamp', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
