# Generated by Django 3.1.7 on 2021-03-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20210304_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.TextField(blank=True, max_length=500, primary_key=True, serialize=False),
        ),
    ]
