# Generated by Django 3.1.7 on 2021-03-31 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20210331_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tstamp',
            new_name='published',
        ),
    ]
