# Generated by Django 3.1.7 on 2021-03-31 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20210331_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='api_token',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
