# Generated by Django 3.1.7 on 2021-03-31 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20210330_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='hostname',
            new_name='hostserver',
        ),
    ]
