# Generated by Django 3.1.6 on 2021-03-10 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20210310_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='id',
            new_name='comment_id',
        ),
    ]
