# Generated by Django 3.1.7 on 2021-03-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20210330_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='hostserver',
            field=models.URLField(),
        ),
    ]
