# Generated by Django 3.1.7 on 2021-04-15 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_postsearch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostSearch',
        ),
    ]
