# Generated by Django 3.1.7 on 2021-03-05 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20210304_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='id',
            new_name='UUid',
        ),
    ]
