# Generated by Django 3.1.7 on 2021-03-04 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20210304_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='need_authorization',
            new_name='UsersNeedAuthentication',
        ),
    ]
