# Generated by Django 3.1.7 on 2021-03-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20210330_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='consistent_id',
            field=models.TextField(blank=True, primary_key=True, serialize=False),
        ),
    ]
