# Generated by Django 3.1.6 on 2021-03-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20210310_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='author',
            name='userid',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(null=True),
        ),
    ]
