# Generated by Django 3.1.7 on 2021-03-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20210304_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='boink',
            field=models.BooleanField(default=True),
        ),
    ]
