# Generated by Django 2.1.7 on 2021-03-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20210321_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
