# Generated by Django 3.1.7 on 2021-03-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20210322_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author_privacy',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='author',
            name='consistent_id',
            field=models.TextField(blank=True, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
