# Generated by Django 3.1.7 on 2021-03-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20210304_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercreation',
            old_name='Authorized',
            new_name='authorized',
        ),
        migrations.AddField(
            model_name='usercreation',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercreation',
            name='name',
            field=models.CharField(default='testname', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercreation',
            name='userid',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
