# Generated by Django 3.1.7 on 2021-04-01 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20210331_0040'),
        ('firstapp', '0006_author_api_token'),
    ]

    operations = [
    ]
