# Generated by Django 3.1.6 on 2021-03-11 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20210310_2226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
