# Generated by Django 3.1.7 on 2021-04-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_merge_20210401_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
