# Generated by Django 3.1.7 on 2021-03-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_remove_author_boink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='UUid',
        ),
        migrations.AddField(
            model_name='author',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
