# Generated by Django 3.1.6 on 2021-03-13 08:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('comment_text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.author')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
