# Generated by Django 3.1.7 on 2021-03-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_auto_20210326_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.TextField(blank=True),
        ),
    ]
