# Generated by Django 3.1.7 on 2021-04-15 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_delete_postsearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSearch',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='firstapp.post')),
            ],
            bases=('firstapp.post',),
        ),
    ]
