# Generated by Django 3.1.7 on 2021-04-10 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_auto_20210409_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='from_user',
            field=models.TextField(blank=True, null=True),
        ),
    ]
