# Generated by Django 3.1.7 on 2021-03-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_auto_20210304_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='github_username',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
