# Generated by Django 3.1.7 on 2021-04-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_auto_20210409_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='published',
            field=models.CharField(default='', max_length=50),
        ),
    ]
